name: Pull request
on:
  pull_request:
    types:
      - opened
    branches:
      - main # main
      - "dev-*" # dev-001
      - "feat/**" # feat/new
  workflow_dispatch:
  push:
    branches:
      - main # main
      - "dev-*" # dev-001
      - "feat/**" # feat/new
    paths-ignore:
      - ".github/workflows/*"
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Output name of the event that triggered the workflow run.
        run: echo "${{ toJSON(github.event_name) }}"
      - name: Get code
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm ci
      - name: Test code
        run: npm run test
      - name: Build code
        run: npm run build
      - name: Deploy project
        run: echo "Deploying..."
